### ISSUE TITLE
Text in French mungled in the first screen after selecting language

### ISSUE THREAD

**Issue by cardpuncher** [shidel/FDI#11]
On 1.3-RC3, when the user selects the French language, the first screen is weird: the text is all over the place, the OS name is missing, and some letters are missing as well. See the screenshot below.

![2020-06-01-233604_scrot](https://user-images.githubusercontent.com/64688741/83747330-22921f80-a669-11ea-91b9-fdf4436bea77.png)

Additionally, when the installation is completed, the welcome to the system message has a "Parameter error". See below, at the top of the screenshot:

![2020-06-01-232023_scrot](https://user-images.githubusercontent.com/64688741/83747615-8ddbf180-a669-11ea-8f70-95b49631fbb9.png)

Is this something to be fixed by the translator or the coder?

**Comment by shidel** [comment]
> On 1.3-RC3, when the user selects the French language, the first screen is weird: the text is all over the place, the OS name is missing, and some letters are missing as well. See the screenshot below.
 
This is definitely two minor issues in the FR/FDSETUP.DEF file. The frame dimensions for that dialog in French. And the line breaks of the actual text "/p" switches.
 
> Additionally, when the installation is completed, the welcome to the system message has a "Parameter error". See below, at the top of the screenshot:
> 

To save space, Parameter error is pretty much used for any error regarding incorrect command line or resource file (like a FDSET.DEF) string options.

When it that occurs from a translation, it is usually do to  lack of spacing in parameters or quoting issues ( ' or " ). 

A quick  look at that line:

**AUTO_WELCOME=Bienvenue au système d'exploitation /fGreen %1 /fCyan %2 /fGray ( /s- /fYellow "%3" /fGray )**

I see it is a quote issue. The word _d'exploitation_ contains a ' character. This causes the parser to switch into quoted text mode. However, it is unable to locate the other end of the qoute and throws and error message. That portion of text would need to be quoted so that quote does not cause an error. 

**AUTO_WELCOME=Bienvenue au système "d'exploitation" /fGreen %1 /fCyan %2 /fGray ( /s- /fYellow "%3" /fGray )**

or 

**AUTO_WELCOME="Bienvenue au système d'exploitation" /fGreen %1 /fCyan %2 /fGray ( /s- /fYellow "%3" /fGray )**

But not entire line. Quotes there would cause everything including the /fGreen and %1 to displayed as-is. 

More on quoting. Let's say there was a message that an end user would see as:

_Hello Bob. Did you see the story "Today at Bob's House!"_

It gets a little tricky but could look like this:

**Hello %1 /s- '. Did you see the story "Today at ' %1 "'s " 'House!"'** 

> Is this something to be fixed by the translator or the coder?

In a perfect world, neither as I would have created more tools to adjust the Frame for the French welcome message automatically (and may do this eventually) and have created more and better tools for the translator to quickly catch syntax issues. 

However, as things stand at present, I more or less need to rely on the community to point out these types of things. So, I can then go back and adjust them. It is not practical for me to try and proof-read the 50+ screens the installer can display for a specific language. Combine that with all the other languages, and we are taking nearly hundreds and hundreds of text screens that I cannot actually read. 

But, between my sporadic inspection of the translation files, the community pointing out issues and the excellent work of the translators, it will all eventually be perfect.

Seriously, you translators do a great job. It's one thing to translate _"2.1=Press a key"_ and it is another wading through some of the language resource file like in the installer with all those switches, variables, quoting and unique syntax rules. It is amazing work.

**Comment by shidel** [comment]
Out of curiosity, is it easier, harder or about the same when translating the different styles of language resource files like:

**_1.1=Language Program
1.2=Hello User
1.3=read error
1.4=disk full error_**

or

**_PROG_TITLE=Language Program
MAIN_GREATING=Hello User
ERR_LOAD=read error
ERR_NOSPACE=disk full error_**

I would think things like  "**_ERR_LOAD=_**" may or may not give you a hint towards how you would translate the text. But, "**_1.3_**" really doesn't do anything except kinda group similar things together.  But, I'm extremely biased on it. :-)

**Comment by cardpuncher** [comment]
On 4.06.2020 18:27, shidel wrote:
> Out of curiosity, is it easier, harder or about the same when
> translating the different styles of language resource files like:
> 
> */1.1=Language Program
> 
> or
> 
> */PROG_TITLE=Language Program
>
> I would think things like "*/ERR_LOAD=/*" may or may not give you a hint
> towards how you would translate the text. But, "*/1.3/*" really doesn't
> do anything except kinda group similar things together. But, I'm
> extremely biased on it. :-)

You're right, something like /1.1=  doesn't give any context information
at all whereas */PROG_TITLE= is somewhat better. That said, the best
option would be to use a gettext file with all the context information
embedded in it. I know it's much more work, but PerditionC will maybe
work on that (see
<https://sourceforge.net/p/freedos/mailman/message/37014935/>). In the
meantime, I would prefer the second set.

**Comment by shidel** [comment]
Anyhow I corrected the syntax for the boot "welcome' message and adjusted the dimensions and line breaks on the installer Welcome Screen to ![Screen Shot 2020-06-04 at 12 35 18 PM](https://user-images.githubusercontent.com/10198034/83785961-0e95f000-a660-11ea-898a-2912925cc29c.png)

**Comment by cardpuncher** [comment]
On 4.06.2020 19:39, shidel wrote:
> Anyhow I corrected the syntax for the boot "welcome' message and
> adjusted the dimensions and line breaks on the installer Welcome Screen
> to Screen Shot 2020-06-04 at 12 35 18 PM
> <https://user-images.githubusercontent.com/10198034/83785961-0e95f000-a660-11ea-898a-2912925cc29c.png>

That looks perfect! One final question tho, when the installation is
finished do you still see the "Parameter error" message?

**Comment by shidel** [comment]
> On 4.06.2020 18:27, shidel wrote: Out of curiosity, is it easier, harder or about the same when translating the different styles of language resource files like: */1.1=Language Program or */PROG_TITLE=Language Program I would think things like "*/ERR_LOAD=/*" may or may not give you a hint towards how you would translate the text. But, "*/1.3/*" really doesn't do anything except kinda group similar things together. But, I'm extremely biased on it. :-)
> You're right, something like /1.1= doesn't give any context information at all whereas */PROG_TITLE= is somewhat better. That said, the best option would be to use a gettext file with all the context information embedded in it. 

:-) I though that would be the case. But, I'm biased towards my own engines. 

I know it's much more work, but PerditionC will maybe work on that (see <https://sourceforge.net/p/freedos/mailman/message/37014935/>). In the meantime, I would prefer the second set.

I don't know. I'm not familiar with Weblate. So, a couple things here may be wrong. But, a cursory look at Weblate brings up some concerns. It's only mostly free unless you self host it ($). Long term support? Will it be around 20 years from now when there is a FreeCOM recompile and 25 year old translations are needed? Will the programmer properly understand the translation to change simple text back into complex parsed strings? How well does it handle updates and additions to the program (ie new program version, may have numerous new strings that need translated)? IDK. When I get some free time, I'll have to look into it more closely. Perhaps it or something like it could be integrated into the workflow. 

I don't know much about other programmers backend handling of translation files. But, the stuff I create for my programs is tends to be very flexible (except for PGME). For example, it could use the '1.2, etc" for entries. But, I prefer the named keys like "APP_TITLE" it's easier for me to find and change things. Also, the files can have just about anything in them with comments and plain text to help understand how any entry is used. I should put more and better comments in the English files version to assist in translation. 

While I don't have the numbers, I suspect that over half of the users of FreeDOS do not speak English as their native language (or at all). Making it easier for translators definitely gives those users a better experience when using FreeDOS. I personally feel it is one of the areas we can improve.

**Comment by shidel** [comment]
> On 4.06.2020 19:39, shidel wrote: Anyhow I corrected the syntax for the boot "welcome' message and adjusted the dimensions and line breaks on the installer Welcome Screen to Screen Shot 2020-06-04 at 12 35 18 PM <https://user-images.githubusercontent.com/10198034/83785961-0e95f000-a660-11ea-898a-2912925cc29c.png>
> That looks perfect! One final question tho, when the installation is finished do you still see the "Parameter error" message?

I adjusted that to.

I made changes using the LiveCD then mirrored what I changed in the sources. Absolute verification that it is "good" won't come until I have the RBE build a release. But, unless I made a typo, it should be fine now. I did notice the next page had a ? all by itself on a line. So, I'll need to go through and do a couple more tweaks for aesthetic purposes.

So, I'll leave this thread open as a reminder to run through it and make those adjustments before the next build (Final or Devel only)
