### ISSUE TITLE
Installation guide. 

### ISSUE THREAD

**Issue by ghost** [shidel/FDI#3]
On web page: "Creating a FDI based FreeDOS installer shidel edited this page on May 24, 2017"
Both the 512mb and the 32mb images links goes to: "There are no downloads available for "FDI-USB.zip" at this time." and There are no downloads available for "FDI-SLIM.zip" at this time.."
The YouTube video https://youtu.be/rKAq7HEQ1oE is out of date.

**Comment by shidel** [comment]
Thanks for catching the bad links. I completely forgot about updating them in the wiki when I did some restructuring on LOD.BZ site. Since the video, the 32/512 USB images had been renamed and eventually became the official release versions for FreeDOS 1.2. I updated the the wiki links to point to my mirror for FreeDOS releases and software repo at https://fd.lod.bz 
As for the video, I don’t think there have been any other major changes. I think just the file names and links are obsolete. But, there could be other outdated issues. When I get some free time, I’ll have to go over it and see if it needs updated.
